"""auto

Revision ID: 21677c824db9
Revises: c1fadc4bf7da
Create Date: 2025-08-09 13:47:44.309149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21677c824db9'
down_revision = 'c1fadc4bf7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remember_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remember_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_remember_devices_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_remember_devices_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remember_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remember_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_remember_devices_token_hash'))

    op.drop_table('remember_devices')
    # ### end Alembic commands ###
