"""init

Revision ID: 2a5d406a1e36
Revises: 
Create Date: 2025-08-08 23:49:24.753334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5d406a1e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=95), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('not_before', sa.DateTime(), nullable=True),
    sa.Column('not_after', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_certificates_fingerprint_sha256'), ['fingerprint_sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_certificates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_certificates_fingerprint_sha256'))

    op.drop_table('user_certificates')
    op.drop_table('users')
    # ### end Alembic commands ###
